# Generated by Django 4.1.5 on 2023-01-26 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="watchlist",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="watchlist_app.watchlist",
            ),
            preserve_default=False,
        ),
    ]
